[tool.poetry]
name = "graphql_sdk_gen"
version = "0.1.0"
description = "Codegen for Python GraphQL clients"
authors = ["Mirumee Software <hello@mirumee.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.3"
graphql-core = "^3.2.1"
toml = "^0.10.2"
black = "^22.8.0"
isort = "^5.10.1"
httpx = "^0.23.0"
pydantic = "^1.10.2"
autoflake = "^1.7.7"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"
pylint = "^2.15.3"
mypy = "^0.971"
types-toml = "^0.10.8"
pytest-mock = "^3.8.2"
pytest-asyncio = "^0.19.0"

[tool.poetry.scripts]
graphql-sdk-gen = "graphql_sdk_gen.main:main"

[tool.pylint.messages_control]
max-line-length = 88
disable = [
    "missing-docstring",
    "redefined-outer-name",
    "too-few-public-methods",
    "too-many-instance-attributes",
    "too-many-arguments",
    "duplicate-code",
    "no-name-in-module",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[graphql-sdk-gen]
schema_path = "."
queries_path = "."
