[tool.poetry]
name = "graphql-sdk-gen"
version = "0.1.0"
description = "Codegen for Python GraphQL clients"
authors = ["Mateusz Sopiński <mateusz.sopinski@mirumee.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.3"
graphql-core = "^3.2.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
