[tool.poetry]
name = "graphql_sdk_gen"
version = "0.1.0"
description = "Codegen for Python GraphQL clients"
authors = ["Mateusz Sopiński <mateusz.sopinski@mirumee.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.3"
graphql-core = "^3.2.1"
toml = "^0.10.2"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"

[tool.poetry.scripts]
graphql-sdk-gen = "graphql_sdk_gen.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[graphql-sdk-gen]
