name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -e .[dev]
    - name: Pytest
      run: |
        pytest
    - name: Linters
      run: |
        pylint graphql_sdk_gen tests
        mypy graphql_sdk_gen --ignore-missing-imports
        black --check .
        isort . --check-only
