name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Install dependencies
      run: poetry install --no-interaction
    - name: Pytest
      run: |
        source .venv/bin/activate
        pytest
    - name: Linters
      run: |
        source .venv/bin/activate
        pylint graphql_sdk_gen tests
        mypy graphql_sdk_gen --ignore-missing-imports
        black --check .
